export interface Country {
  name: string;
  code: string;
  flag: string;
  dial: string;
}

export const countries: Country[] = [
  { name: "Afghanistan", code: "AF", flag: "🇦🇫", dial: "+93" },
  { name: "Albania", code: "AL", flag: "🇦🇱", dial: "+355" },
  { name: "Algeria", code: "DZ", flag: "🇩🇿", dial: "+213" },
  { name: "Argentina", code: "AR", flag: "🇦🇷", dial: "+54" },
  { name: "Australia", code: "AU", flag: "🇦🇺", dial: "+61" },
  { name: "Austria", code: "AT", flag: "🇦🇹", dial: "+43" },
  { name: "Bangladesh", code: "BD", flag: "🇧🇩", dial: "+880" },
  { name: "Belgium", code: "BE", flag: "🇧🇪", dial: "+32" },
  { name: "Brazil", code: "BR", flag: "🇧🇷", dial: "+55" },
  { name: "Canada", code: "CA", flag: "🇨🇦", dial: "+1" },
  { name: "Chile", code: "CL", flag: "🇨🇱", dial: "+56" },
  { name: "China", code: "CN", flag: "🇨🇳", dial: "+86" },
  { name: "Colombia", code: "CO", flag: "🇨🇴", dial: "+57" },
  { name: "Czech Republic", code: "CZ", flag: "🇨🇿", dial: "+420" },
  { name: "Denmark", code: "DK", flag: "🇩🇰", dial: "+45" },
  { name: "Egypt", code: "EG", flag: "🇪🇬", dial: "+20" },
  { name: "Finland", code: "FI", flag: "🇫🇮", dial: "+358" },
  { name: "France", code: "FR", flag: "🇫🇷", dial: "+33" },
  { name: "Germany", code: "DE", flag: "🇩🇪", dial: "+49" },
  { name: "Ghana", code: "GH", flag: "🇬🇭", dial: "+233" },
  { name: "Greece", code: "GR", flag: "🇬🇷", dial: "+30" },
  { name: "India", code: "IN", flag: "🇮🇳", dial: "+91" },
  { name: "Indonesia", code: "ID", flag: "🇮🇩", dial: "+62" },
  { name: "Iran", code: "IR", flag: "🇮🇷", dial: "+98" },
  { name: "Iraq", code: "IQ", flag: "🇮🇶", dial: "+964" },
  { name: "Ireland", code: "IE", flag: "🇮🇪", dial: "+353" },
  { name: "Israel", code: "IL", flag: "🇮🇱", dial: "+972" },
  { name: "Italy", code: "IT", flag: "🇮🇹", dial: "+39" },
  { name: "Jamaica", code: "JM", flag: "🇯🇲", dial: "+1876" },
  { name: "Japan", code: "JP", flag: "🇯🇵", dial: "+81" },
  { name: "Kenya", code: "KE", flag: "🇰🇪", dial: "+254" },
  { name: "Malaysia", code: "MY", flag: "🇲🇾", dial: "+60" },
  { name: "Mexico", code: "MX", flag: "🇲🇽", dial: "+52" },
  { name: "Morocco", code: "MA", flag: "🇲🇦", dial: "+212" },
  { name: "Netherlands", code: "NL", flag: "🇳🇱", dial: "+31" },
  { name: "New Zealand", code: "NZ", flag: "🇳🇿", dial: "+64" },
  { name: "Nigeria", code: "NG", flag: "🇳🇬", dial: "+234" },
  { name: "Norway", code: "NO", flag: "🇳🇴", dial: "+47" },
  { name: "Pakistan", code: "PK", flag: "🇵🇰", dial: "+92" },
  { name: "Peru", code: "PE", flag: "🇵🇪", dial: "+51" },
  { name: "Philippines", code: "PH", flag: "🇵🇭", dial: "+63" },
  { name: "Poland", code: "PL", flag: "🇵🇱", dial: "+48" },
  { name: "Portugal", code: "PT", flag: "🇵🇹", dial: "+351" },
  { name: "Romania", code: "RO", flag: "🇷🇴", dial: "+40" },
  { name: "Russia", code: "RU", flag: "🇷🇺", dial: "+7" },
  { name: "Saudi Arabia", code: "SA", flag: "🇸🇦", dial: "+966" },
  { name: "Singapore", code: "SG", flag: "🇸🇬", dial: "+65" },
  { name: "South Africa", code: "ZA", flag: "🇿🇦", dial: "+27" },
  { name: "South Korea", code: "KR", flag: "🇰🇷", dial: "+82" },
  { name: "Spain", code: "ES", flag: "🇪🇸", dial: "+34" },
  { name: "Sweden", code: "SE", flag: "🇸🇪", dial: "+46" },
  { name: "Switzerland", code: "CH", flag: "🇨🇭", dial: "+41" },
  { name: "Thailand", code: "TH", flag: "🇹🇭", dial: "+66" },
  { name: "Turkey", code: "TR", flag: "🇹🇷", dial: "+90" },
  { name: "Ukraine", code: "UA", flag: "🇺🇦", dial: "+380" },
  { name: "United Arab Emirates", code: "AE", flag: "🇦🇪", dial: "+971" },
  { name: "United Kingdom", code: "GB", flag: "🇬🇧", dial: "+44" },
  { name: "United States", code: "US", flag: "🇺🇸", dial: "+1" },
  { name: "Vietnam", code: "VN", flag: "🇻🇳", dial: "+84" },
];
